version: '3'
services:
  warproxy:
    image: ghcr.io/kingcc/warproxy:latest
    container_name: warproxy
    restart: always
    environment:
      - WARP_PLUS=true
      - TZ=Asia/Ho_Chi_Minh
      - ENDPOINT=162.159.192.12
      - DNS=1.1.1.1
      # - USERNAME=admin
      # - PASSWORD=pass
    ports:
      - 1080:1080